### ISSUE TITLE
File IO error EINVAL

### ISSUE THREAD

**Issue by roba91** [miroof/node-virtual-gamepads#12]
After managing to install and run your program on my machine I'm receiving an error every time I connect to the server (i.e. open the url)

    Missing error handler on `socket`.
    Error: EINVAL, invalid argument
        at Object.fs.writeSync (fs.js:533:18)
        at virtual_gamepad.sendEvent (/home/rouven/D_Data/code/git/roba91/node-virtual-gamepads/app/virtual_gamepad.js:112:12)
        at virtual_gamepad_hub.sendEvent (/home/rouven/D_Data/code/git/roba91/node-virtual-gamepads/app/virtual_gamepad_hub.js:59:37)
        at Socket.<anonymous> (/home/rouven/D_Data/code/git/roba91/node-virtual-gamepads/main.js:48:20)
        at Socket.EventEmitter.emit (events.js:95:17)
        at Socket.onevent (/home/rouven/D_Data/code/git/roba91/node-virtual-gamepads/node_modules/socket.io/lib/socket.js:330:8)
        at Socket.onpacket (/home/rouven/D_Data/code/git/roba91/node-virtual-gamepads/node_modules/socket.io/lib/socket.js:290:12)
        at Client.ondecoded (/home/rouven/D_Data/code/git/roba91/node-virtual-gamepads/node_modules/socket.io/lib/client.js:193:14)
        at Decoder.Emitter.emit (/home/rouven/D_Data/code/git/roba91/node-virtual-gamepads/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
        at Decoder.add (/home/rouven/D_Data/code/git/roba91/node-virtual-gamepads/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)

Server is running on a Linux Mint 17.1 (64 bit) machine, with root permissions, a file `/dev/uinput` exists and root has read and write permissions for it.

Any idea what I'm missing?

**Comment by roba91** [comment]
Oh wow, I found a fix for it. It took me like 2 hours and google didn't want to help me...

If you are running on ubuntu or a system that does not come with header-files (dev-packages) pre-installed

    sudo apt-get install libudev-dev

fixes the problem.
