### ISSUE TITLE
Error ioctl at launch (But work)

### ISSUE THREAD

**Issue by MikaXII** [miroof/node-virtual-gamepads#37]
```
Error on gamepad create dev:
 { Error: ioctl -22
    at module.exports (/usr/node-virtual-gamepads/node_modules/ioctl/index.js:6:17)
    at /usr/node-virtual-gamepads/app/virtual_gamepad.js:82:19
    at FSReqWrap.wrapper [as oncomplete] (fs.js:747:5) code: -22, errno: -22, syscall: [Function] }
Retry to create gamepad
Error on gamepad create dev:
 { Error: ioctl -22
    at module.exports (/usr/node-virtual-gamepads/node_modules/ioctl/index.js:6:17)
    at /usr/node-virtual-gamepads/app/virtual_gamepad.js:82:19
    at FSReqWrap.wrapper [as oncomplete] (fs.js:747:5) code: -22, errno: -22, syscall: [Function] }
Retry to create gamepad
Error on gamepad create dev:
 { Error: ioctl -22
    at module.exports (/usr/node-virtual-gamepads/node_modules/ioctl/index.js:6:17)
    at /usr/node-virtual-gamepads/app/virtual_gamepad.js:82:19
    at FSReqWrap.wrapper [as oncomplete] (fs.js:747:5) code: -22, errno: -22, syscall: [Function] }
Retry to create gamepad
Gamepad connected
```

**Comment by roba91** [comment]
I actually know that that error occurs some times. This is why I changed `virtual_gamepad.js` to try to create the device up to–I think–5 times before it finally gives up and crashes. Sadly, I couldn't find out why it does so.
